"""The published capability count has to say what it was computed against.

docs/FEATURES.md is generated on a development machine, where 3.6 GB of trained weights
sit in `models/`. Continuous integration has no weights, so the rows that exercise a real
model cannot reach `verified` there, and the runner reaches a lower count than the
document publishes -- 153 against 160 at the time this was written.

Neither number is wrong. Both are honest about their own evidence. What was not honest
was publishing the higher one with nothing on its face to explain it, so a reader who
cloned the repository and ran the same command got a smaller number than the document
claimed and had no way to know why.
"""

from __future__ import annotations

from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "tools"))

from feature_status import evidence_base  # noqa: E402


def test_the_generated_document_states_its_evidence_base(tmp_path, monkeypatch):
    """Asserted against the generator, not the checked-in file.

    docs/FEATURES.md is regenerated by whoever runs the tool next, and testing the file
    would fail on a tree that simply has not been regenerated yet -- which says nothing
    about whether the tool is right.
    """
    import feature_status
    from docs.features.registry import ALL_FEATURES

    monkeypatch.setattr(feature_status, "REPO_ROOT", tmp_path)
    (tmp_path / "docs").mkdir()
    results = [(feature, feature.claimed, "") for feature in ALL_FEATURES[:3]]
    feature_status.write_markdown(results, {"verified": 3}, 3)

    text = (tmp_path / "docs" / "FEATURES.md").read_text(encoding="utf-8")
    assert "trained model" in text, (
        "the document would publish a count without saying whether the weights were "
        "present, which makes it a number only one machine reproduces"
    )
    # And it has to appear before the table, not in a footnote below the 167 rows.
    assert text.index("trained model") < text.index("| Status | Count | Share |")


def test_it_names_the_weights_when_they_are_installed():
    if not list((REPO_ROOT / "models").rglob("*.onnx")):
        return  # covered by the other direction below
    line = evidence_base()
    assert "trained models installed" in line
    assert "GB" in line
    # The point of the note is that the reader can find the lower number themselves.
    assert "feature_status.py" in line


def test_it_says_so_when_there_are_no_weights(tmp_path, monkeypatch):
    """The CI reading, which is the reproducible floor."""
    import feature_status

    monkeypatch.setattr(feature_status, "REPO_ROOT", tmp_path)
    line = feature_status.evidence_base()
    assert "without the trained model weights" in line
    assert "fresh clone reproduces" in line
    # It must not claim a size or a model count it does not have.
    assert "GB" not in line
