"""Structural checks on the Helm chart.

These are not a substitute for `helm lint` and `helm template`, and they do not pretend
to be: without the helm binary the Go templates cannot be rendered, so nothing here
proves the chart produces valid Kubernetes objects. What they do check is the set of
mistakes that survive a successful render -- a default password, a probe pointing at
liveness when it should check readiness, a database on an emptyDir.

A chart that lints cleanly and ships a working default credential is worse than one that
fails to render.
"""

from __future__ import annotations

from pathlib import Path

import pytest

yaml = pytest.importorskip("yaml")

CHART = Path(__file__).resolve().parents[1] / "infrastructure" / "helm" / "opendronekit"
TEMPLATES = CHART / "templates"


@pytest.fixture(scope="module")
def values() -> dict:
    return yaml.safe_load((CHART / "values.yaml").read_text(encoding="utf-8"))


class TestChartMetadata:
    def test_the_chart_declares_itself(self) -> None:
        chart = yaml.safe_load((CHART / "Chart.yaml").read_text(encoding="utf-8"))
        assert chart["apiVersion"] == "v2"
        assert chart["name"] == "opendronekit"
        assert chart["version"]

    def test_every_component_has_a_template(self) -> None:
        names = {p.name for p in TEMPLATES.iterdir()}
        for required in ("api-deployment.yaml", "worker-deployment.yaml",
                         "postgis.yaml", "secret.yaml", "_helpers.tpl"):
            assert required in names, f"{required} missing from the chart"


class TestNoDefaultCredentials:
    """The failure mode this chart is most likely to cause.

    "Change this in production" is advice nobody reads in time. A default that works is
    a default that reaches production, so rendering must fail instead.
    """

    def test_no_secret_has_a_usable_default(self, values: dict) -> None:
        for key, value in values["secrets"].items():
            assert value == "", f"secrets.{key} ships a default; it must be empty"

    def test_rendering_fails_without_secrets(self) -> None:
        helpers = (TEMPLATES / "_helpers.tpl").read_text(encoding="utf-8")
        assert "fail" in helpers, "nothing stops a deploy with no credentials set"
        assert "odkSecretKey" in helpers
        assert "postgresPassword" in helpers

    def test_an_externally_managed_secret_is_supported(self, values: dict) -> None:
        # Refusing defaults is only reasonable if there is a real alternative to them.
        assert "existingSecret" in values["secrets"]
        assert "existingSecret" in (TEMPLATES / "_helpers.tpl").read_text(encoding="utf-8")


class TestProbesCheckDependencies:
    def test_readiness_uses_the_dependency_checking_endpoint(self) -> None:
        """/health/ready hits the database and object store; /health/live does not.

        Using liveness for readiness would send traffic to a pod that cannot reach
        PostGIS, and restarting it -- which is what a failing liveness probe does --
        would not fix a database that is down.
        """
        deployment = (TEMPLATES / "api-deployment.yaml").read_text(encoding="utf-8")
        assert "/health/ready" in deployment
        assert "/health/live" in deployment
        ready_at = deployment.index("readinessProbe")
        assert "/health/ready" in deployment[ready_at:ready_at + 400]


class TestDataDurability:
    def test_the_database_is_a_statefulset_with_a_claim(self) -> None:
        # Survey data is the one thing here that cannot be regenerated by re-running a
        # job, so it must not sit on an emptyDir.
        raw = (TEMPLATES / "postgis.yaml").read_text(encoding="utf-8")
        assert "kind: StatefulSet" in raw
        assert "volumeClaimTemplates" in raw
        # Comments explain WHY an emptyDir would be wrong, so strip them before checking
        # that none is actually declared. Otherwise the reasoning trips its own test.
        manifest = "".join(
            line for line in raw.splitlines(keepends=True)
            if not line.lstrip().startswith("#")
        )
        assert "emptyDir" not in manifest


class TestWorkerResources:
    def test_the_worker_has_a_memory_limit(self, values: dict) -> None:
        # Photogrammetry is memory-bound before it is CPU-bound. An unlimited worker is
        # OOM-killed mid-reconstruction and loses hours rather than degrading.
        limits = values["worker"]["resources"]["limits"]
        assert "memory" in limits

    def test_the_worker_requests_less_than_it_may_use(self, values: dict) -> None:
        resources = values["worker"]["resources"]
        request = resources["requests"]["memory"]
        limit = resources["limits"]["memory"]
        assert request.endswith("Gi") and limit.endswith("Gi")
        assert int(request[:-2]) <= int(limit[:-2])


class TestFullValidationIsStillNeeded:
    def test_this_suite_does_not_claim_to_render_the_chart(self) -> None:
        """Recorded so the registry row is not read as more than it is.

        Nothing here runs helm, so nothing here proves the templates produce valid
        Kubernetes objects. `helm lint` and `helm template` against a real cluster are
        what move inf.k8s from implemented to verified.
        """
        import shutil

        if shutil.which("helm"):
            pytest.skip("helm is available; run `helm lint` and `helm template` directly")
        assert True
