/*
 * The demo contract, mirrored from core/demo_mode.py.
 *
 * The cockpit shipped invented content that looked exactly like a real Indian survey:
 * "Bhopal Warehouse", "NH-46 Corridor", "Kalyan Solar Farm", coordinates at 28.6139 N
 * 77.2090 E (Delhi), 412 GB of storage, processing job #4471 at 34 per cent. None of it
 * was marked, except a chip in the status bar -- which was itself clipped off the screen
 * at 1600px, so in practice nothing marked it at all.
 *
 * That is the one place this codebase fabricated. Everywhere else a model refuses rather
 * than guesses and a status is computed from tests that ran. The product's shop window
 * should not be the exception.
 *
 * core/demo_mode.py already solved this properly for the backend, and its choices are
 * the ones worth copying rather than reinventing:
 *
 *   Null Island (0, 0)  A real inspection is never here. A reader who misses every
 *                       label still cannot mistake these coordinates for a site.
 *   The epoch           Same argument for time.
 *   DEMO operator       Names a person who does not exist.
 *
 * Keeping the two in step matters: if the desktop demo and the API demo disagree about
 * what synthetic looks like, one of them is teaching a user the wrong tell.
 */

import { DEMO_DATA } from "./demo-data.js";

/** The real measurements, generated by tools/build_demo_data.py. */
export const DATA = DEMO_DATA;

export const DEMO = {
  LAT: 0.0,
  LON: 0.0,
  TIMESTAMP: "1970-01-01T00:00:00+00:00",
  CLOCK: "00:00:00",
  OPERATOR: "DEMO",
  ORG: "DEMO organisation",
  PROVENANCE: DEMO_DATA.note,
  // Kept because core/demo_mode.py stamps it on API demo artefacts, and the two
  // surfaces must not disagree about what that marker says.
  SYNTHETIC_PROVENANCE:
    "SYNTHETIC: generated by OpenDroneKit demo mode. Not a measurement. " +
    "No aircraft flew and no sensor recorded this.",
  // Named so the label survives being read out of context -- a screenshot of one panel
  // still says what it is.
  // The example project is a real reconstruction this repository measured, not an
  // invented site. The remaining entries are the models it has installed, so every row
  // in the tree points at something that exists on disk with a digest.
  SITES: [
    DEMO_DATA.project.name,
    ...DEMO_DATA.models.slice(0, 3).map((model) => model.key),
  ],
  // Says what it is. The content IS measured -- it is this project's own validation
  // results -- but it is not a live connection to a running survey, and conflating the
  // two is the thing worth preventing.
  BANNER:
    "EXAMPLE DATA — real measurements from this repository, not a live connection",
};

/** The coordinate readout, in the same shape the canvas expects. */
export function demoCoords() {
  return `<span>${DEMO.LAT.toFixed(4)} N &nbsp; ${DEMO.LON.toFixed(4)} E &nbsp; EPSG:4326 &nbsp; z16</span>`;
}

/**
 * Whether this session is showing demo content.
 *
 * Off by default. An empty cockpit is the honest state for a product with no project
 * open, and it is also the state that tells a new user what to do next -- invented
 * projects tell them the software is already full of someone else's work.
 */
export function demoEnabled() {
  if (typeof window === "undefined") return false;
  if (window.ODK_DEMO === true) return true;
  try {
    return new URLSearchParams(window.location.search).get("demo") === "1";
  } catch {
    return false;
  }
}
