/* Generated by tools/build_demo_data.py -- do not edit.
 *
 * Every number here was measured by this project and read out of the model
 * registry, the metrics cards and the feature registry. Regenerate rather than
 * editing: a hand-typed figure drifts from the artefact it describes, and this
 * one would drift inside the product's shop window.
 */

export const DEMO_DATA = {
  "project": {
    "name": "OpenDroneKit Aukerman survey",
    "source": "OpenDroneMap Aukerman dataset",
    "images_registered": "77/77",
    "reprojection_px": 1.27,
    "geo_rmse_m": 1.22,
    "epsg": "EPSG:32617",
    "provenance": "Measured by this project's COLMAP pipeline; reported in README.md."
  },
  "models": [
    {
      "key": "corrosion_severity_segmentation",
      "labels": [
        "good",
        "fair",
        "poor",
        "severe"
      ],
      "input_size": 512,
      "headline": "mean IoU 0.5769",
      "sha256": "edcecd84cc68"
    },
    {
      "key": "crack_presence_classifier",
      "labels": [
        "crack"
      ],
      "input_size": 224,
      "headline": "balanced accuracy 0.9575",
      "sha256": "92a4d1425b60"
    },
    {
      "key": "crack_segmentation",
      "labels": [
        "crack"
      ],
      "input_size": 1024,
      "headline": "IoU 0.6063",
      "sha256": "3391eca15d43"
    },
    {
      "key": "rail_corridor_segmentation",
      "labels": [
        "rail_corridor"
      ],
      "input_size": 512,
      "headline": "IoU 0.681",
      "sha256": "1885757000e8"
    },
    {
      "key": "rail_obstacle_detector",
      "labels": [
        "Barrel",
        "Boulder",
        "Branch",
        "IronRod",
        "Jerrycan",
        "Person"
      ],
      "input_size": 640,
      "headline": "mAP50 0.824",
      "sha256": "7a53c8b9eaea"
    },
    {
      "key": "solar_cell_defect_detector",
      "labels": [
        "black_core",
        "finger",
        "crack",
        "star_crack",
        "thick_line",
        "horizontal_dislocation",
        "vertical_dislocation",
        "short_circuit"
      ],
      "input_size": 1024,
      "headline": "mAP50 0.8835",
      "sha256": "a57676a7141b"
    },
    {
      "key": "solar_thermal_anomaly_classifier",
      "labels": [
        "Cell",
        "Cell-Multi",
        "Cracking",
        "Diode",
        "Diode-Multi",
        "Hot-Spot",
        "Hot-Spot-Multi",
        "No-Anomaly",
        "Offline-Module",
        "Shadowing",
        "Soiling",
        "Vegetation"
      ],
      "input_size": 96,
      "headline": "balanced accuracy 0.724",
      "sha256": "6933a09abff9"
    },
    {
      "key": "structural_multiclass_detector",
      "labels": [
        "Efflorescence",
        "CorrosionStain",
        "Crack",
        "Spallation",
        "ExposedBars",
        "Background"
      ],
      "input_size": 640,
      "headline": "",
      "sha256": "359817c663f4"
    }
  ],
  "metrics": [
    {
      "key": "corrosion_severity_segmentation",
      "mean_iou": 0.576873642472528,
      "per_class": {
        "good": 0.871,
        "fair": 0.498,
        "poor": 0.45,
        "severe": 0.489
      }
    }
  ],
  "capabilities": {
    "verified": 160,
    "implemented": 0,
    "in_progress": 4,
    "not_started": 3,
    "total": 167,
    "source": "docs/FEATURES.md"
  },
  "note": "Example data. Every figure here was measured by this project and read out of models/model_registry.json, models/metrics/ and docs/features/registry.py when the UI was built. It is a real result, not a live connection to a running survey."
};
