"""Core pipeline modules for structural fault analysis."""

# New modules
from .project import ProjectManager, ProjectReadiness, ProjectSummary, AuditEvent, get_manager
from .workflows import WorkflowTemplate, WorkflowReadiness, list_workflow_templates, get_workflow_template, validate_workflow_readiness
from .survey_intelligence import (
    ChangeRegion,
    SelectedROIChangePackage,
    StockpilePackage,
    SurveyChangePackage,
    create_selected_roi_change_package,
    create_stockpile_package,
    create_surface_change_package,
)
from .semantic_engine import (
    ONNXSemanticPredictor,
    SemanticClass,
    SemanticInferenceConfig,
    SemanticInferencePackage,
    SemanticInferenceRefused,
    SemanticModelMetadata,
    SemanticSchema,
    load_semantic_manifest,
    run_semantic_inference,
)
from .measurements import Measurement, create_measurement, list_measurements, delete_measurement, update_measurement, export_measurements, measure_image_distance, measure_polygon_area, measure_crack_length
from .annotations import Annotation, create_annotation, list_annotations, update_annotation, delete_annotation, export_annotations, get_report_annotations
from .drone import DroneTelemetry, CommandResult, DroneClient, MockDroneClient, MAVSDKDroneClient, create_drone_client
from .workers import (
    WORKER_CANCELLED,
    WORKER_COMPLETED,
    WORKER_FAILED,
    WORKER_PENDING,
    WORKER_RUNNING,
    CancellationToken,
    WorkerCancelled,
    WorkerContext,
    WorkerHandle,
    WorkerPool,
    WorkerProgress,
    WorkerResult,
    WorkerStage,
    get_worker_pool,
    run_stages,
    submit_worker,
)
from .mission_manager import (
    MissionManager,
    MissionPlanRequest,
    MissionSaveResult,
    MissionValidationCheck,
    generate_mission,
    get_mission_manager,
    save_mission,
)

from .detection import (
    CorrosionGradingRefused,
    CorrosionSeverityResult,
    CrackDetectionResult,
    DefectHit,
    MetalDefectResult,
    SolarDefectResult,
    StructuralDefectResult,
    detect_cracks,
    grade_corrosion_severity,
    detect_metal_defects,
    detect_solar_defects,
    detect_structural_defects,
    load_image,
)
from .coverage_validation import CoverageValidationConfig, CoverageValidator
from .multisensor import (
    CalibrationProfile,
    MultiSensorConfig,
    MultiSensorProcessor,
    build_capture_bundle_from_folders,
    create_calibration_profile,
    load_calibration_profile,
    load_capture_bundle,
    write_capture_bundle,
)
from .models import (
    ModelSpec,
    ensure_model_layout,
    get_model_spec,
    load_registry,
    migrate_legacy_models,
    model_status,
    resolve_model_path,
    sync_legacy_checkpoint_archive,
)
from .health_scoring import derive_asset_id, evaluate_asset_health, load_asset_health_history
from .pipeline import PipelineConfig, PipelineResult, StructuralFaultPipeline, run_pipeline
from .propagation import CrackPropagationForecaster, PropagationPhysicsConfig, run_fenicsx_phasefield
from .reconstruction import (
    CustomDroneReconstructor,
    ReconstructionResult,
    available_reconstruction_profiles,
)

__all__ = [
    'ONNXSemanticPredictor',
    'SemanticClass',
    'SemanticInferenceConfig',
    'SemanticInferencePackage',
    'SemanticInferenceRefused',
    'SemanticModelMetadata',
    'SemanticSchema',
    'load_semantic_manifest',
    'run_semantic_inference',
    'SelectedROIChangePackage',
    'create_selected_roi_change_package',
    "ProjectManager",
    "ProjectReadiness",
    "ProjectSummary",
    "AuditEvent",
    "get_manager",
    "WorkflowTemplate",
    "WorkflowReadiness",
    "list_workflow_templates",
    "get_workflow_template",
    "validate_workflow_readiness",
    "ChangeRegion",
    "StockpilePackage",
    "SurveyChangePackage",
    "create_stockpile_package",
    "create_surface_change_package",
    "Measurement",
    "create_measurement",
    "list_measurements",
    "delete_measurement",
    "update_measurement",
    "export_measurements",
    "measure_image_distance",
    "measure_polygon_area",
    "measure_crack_length",
    "Annotation",
    "create_annotation",
    "list_annotations",
    "update_annotation",
    "delete_annotation",
    "export_annotations",
    "get_report_annotations",
    "DroneTelemetry",
    "CommandResult",
    "DroneClient",
    "MockDroneClient",
    "MAVSDKDroneClient",
    "create_drone_client",
    "WORKER_PENDING",
    "WORKER_RUNNING",
    "WORKER_COMPLETED",
    "WORKER_FAILED",
    "WORKER_CANCELLED",
    "WorkerCancelled",
    "WorkerProgress",
    "WorkerResult",
    "CancellationToken",
    "WorkerContext",
    "WorkerStage",
    "WorkerHandle",
    "WorkerPool",
    "run_stages",
    "get_worker_pool",
    "submit_worker",
    "MissionPlanRequest",
    "MissionValidationCheck",
    "MissionSaveResult",
    "MissionManager",
    "get_mission_manager",
    "generate_mission",
    "save_mission",
    "CorrosionGradingRefused",
    "CorrosionSeverityResult",
    "CrackDetectionResult",
    "DefectHit",
    "MetalDefectResult",
    "SolarDefectResult",
    "StructuralDefectResult",
    "CoverageValidationConfig",
    "CoverageValidator",
    "CalibrationProfile",
    "MultiSensorConfig",
    "MultiSensorProcessor",
    "build_capture_bundle_from_folders",
    "PipelineConfig",
    "PipelineResult",
    "StructuralFaultPipeline",
    "CrackPropagationForecaster",
    "PropagationPhysicsConfig",
    "CustomDroneReconstructor",
    "ReconstructionResult",
    "available_reconstruction_profiles",
    "detect_cracks",
    "grade_corrosion_severity",
    "detect_metal_defects",
    "detect_solar_defects",
    "detect_structural_defects",
    "load_image",
    "load_capture_bundle",
    "build_capture_bundle_from_folders",
    "write_capture_bundle",
    "load_calibration_profile",
    "create_calibration_profile",
    "ModelSpec",
    "ensure_model_layout",
    "load_registry",
    "get_model_spec",
    "resolve_model_path",
    "model_status",
    "migrate_legacy_models",
    "sync_legacy_checkpoint_archive",
    "derive_asset_id",
    "evaluate_asset_health",
    "load_asset_health_history",
    "run_pipeline",
    "run_fenicsx_phasefield",
]
