"""Explore the whole workflow with no drone, no survey and no ambiguity.

Demo mode exists so someone can see what OpenDroneKit does before owning hardware. It
is also the single most dangerous feature in the project, because everything it produces
looks exactly like the thing this codebase spends its effort refusing to fabricate: a
measurement.

So the rule here is not "label the output" as a courtesy. It is structural:

*Every* artefact carries ``synthetic: True`` and a ``provenance`` string naming demo
mode. Not the report -- every artefact, at every level, so a fragment lifted out of
context still declares itself.

Numbers are deliberately implausible where implausibility is free. Demo sites sit at
Null Island, timestamps are a fixed epoch, and the operator is "DEMO". A reader who
misses the flag still cannot mistake 0.0, 0.0 for a real inspection.

``is_demo_artifact`` exists so the rest of the codebase can refuse to register, export
or publish a demo product. A capability that emits demo data into a real pipeline is a
worse failure than one that does not run at all.

    from core.demo_mode import demo_project, is_demo_artifact
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

# Null Island. Real inspections are never here, and a coordinate pair of zeros is the
# clearest possible signal to anyone reading a map or a CSV without the flag.
DEMO_LAT = 0.0
DEMO_LON = 0.0

# A fixed instant rather than "now", so demo output is byte-identical between runs and
# cannot be mistaken for a survey that happened today.
DEMO_TIMESTAMP = "1970-01-01T00:00:00+00:00"

DEMO_OPERATOR = "DEMO"
DEMO_PROVENANCE = (
    "SYNTHETIC: generated by OpenDroneKit demo mode. Not a measurement. "
    "No aircraft flew and no sensor recorded this."
)

# The marker every demo artefact carries. Checked by name rather than by truthiness so
# a stray True elsewhere cannot impersonate it.
DEMO_MARKER = "synthetic"


def stamp(payload: dict[str, Any]) -> dict[str, Any]:
    """Mark one artefact as synthetic, recursively.

    Nested dictionaries are stamped too. A caller who pulls one detection out of a demo
    report and passes it along should find the flag still attached to it, because that
    is exactly the path by which synthetic data reaches somewhere it should not.
    """
    marked = dict(payload)
    marked[DEMO_MARKER] = True
    marked["provenance"] = DEMO_PROVENANCE
    for key, value in payload.items():
        if isinstance(value, dict):
            marked[key] = stamp(value)
        elif isinstance(value, list):
            marked[key] = [stamp(v) if isinstance(v, dict) else v for v in value]
    return marked


def is_demo_artifact(payload: Any) -> bool:
    """Whether this came from demo mode, at any nesting depth.

    Used to refuse registration, export or publication. Deliberately conservative: a
    structure containing any synthetic fragment is treated as synthetic, because a
    report that is "mostly real" is not a report anyone can act on.
    """
    if isinstance(payload, dict):
        if payload.get(DEMO_MARKER) is True:
            return True
        return any(is_demo_artifact(value) for value in payload.values())
    if isinstance(payload, (list, tuple)):
        return any(is_demo_artifact(item) for item in payload)
    return False


class DemoDataRefused(ValueError):
    """A demo artefact reached somewhere only real measurements belong."""


def refuse_if_demo(payload: Any, *, action: str) -> None:
    """Guard for any path that ships, registers or publishes a product."""
    if is_demo_artifact(payload):
        raise DemoDataRefused(
            f"Refusing to {action}: this artefact was generated by demo mode and is not "
            "a measurement. Demo output exists to show the workflow, never to be "
            "reported as a survey result."
        )


@dataclass
class DemoProject:
    """A whole workflow, explorable with no hardware."""

    name: str = "Demo inspection"
    site_lat: float = DEMO_LAT
    site_lon: float = DEMO_LON
    captured_at: str = DEMO_TIMESTAMP
    operator: str = DEMO_OPERATOR
    findings: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return stamp({
            "name": self.name,
            "site": {"lat": self.site_lat, "lon": self.site_lon,
                     "note": "Null Island: demo sites are never real coordinates."},
            "captured_at": self.captured_at,
            "operator": self.operator,
            "findings": self.findings,
            "capability_note": (
                "Every number here is invented to illustrate the workflow. Nothing was "
                "measured. Model accuracy figures shown in a real report come from held-"
                "out validation; there is no validation behind these."
            ),
        })


def demo_findings() -> list[dict[str, Any]]:
    """Illustrative findings, shaped like real ones but obviously not measured.

    The classes are real class names from shipping models, because the point is to show
    what the pipeline emits. The geometry and confidences are round numbers a real model
    would essentially never produce.
    """
    return [
        {"class": "crack", "confidence": 0.90, "bbox": [100, 100, 200, 200],
         "area_m2": 1.0, "source_model": "crack_segmentation"},
        {"class": "Corrosion", "confidence": 0.80, "bbox": [300, 300, 400, 400],
         "area_m2": 2.0, "source_model": "metal_corrosion_detector"},
        {"class": "black_core", "confidence": 0.70, "bbox": [500, 500, 600, 600],
         "area_m2": 0.5, "source_model": "solar_cell_defect_detector"},
    ]


def demo_project(name: str = "Demo inspection") -> dict[str, Any]:
    """The full demo workflow product, stamped throughout."""
    return DemoProject(name=name, findings=[stamp(f) for f in demo_findings()]).to_dict()
