"""Kaggle kernel: train crack_cls (classification).

Generated by tools/kaggle_kernel.py. Edit the config in the repository, not this file --
a change made here is invisible to everyone reading the repo.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Everything under /kaggle/working is packaged as the kernel's output when the run
# ends. The repo checkout and the unpacked corpus therefore must NOT live there: for
# crack_cls that is 96,092 files Kaggle tries to archive, and the run dies packaging
# them with an empty log, which looks like a crash with no cause. Scratch goes to
# /kaggle/temp, and only the named artefacts are copied into working at the end.
SCRATCH = Path("/kaggle/temp")
REPO = SCRATCH / "OpenDroneKit"
CORPUS = Path("/kaggle/input/odk-crack-cls-corpus")
OUT = SCRATCH / "artifacts"
OUT.mkdir(parents=True, exist_ok=True)


def report_environment() -> str:
    """Print the environment before training rather than after it fails.

    A torch build that does not support the assigned GPU's compute capability still
    runs; it just falls back and takes far longer, which reads as a slow dataset rather
    than a broken install. Printing this at the top of the log makes it obvious.
    """
    import torch

    print("torch     :", torch.__version__)
    print("cuda built:", torch.version.cuda)
    print("cuda avail:", torch.cuda.is_available())
    if torch.cuda.is_available():
        index = torch.cuda.current_device()
        major, minor = torch.cuda.get_device_capability(index)
        print("device    :", torch.cuda.get_device_name(index))
        print("capability: sm_{}{}".format(major, minor))
        supported = torch.cuda.get_arch_list()
        print("torch arch:", ", ".join(supported))
        if f"sm_{major}{minor}" not in supported:
            print(
                f"This torch does not support sm_{major}{minor}; every CUDA kernel "
                "launch will fail with 'no kernel image is available'."
            )
            return f"sm_{major}{minor}"
    else:
        print("WARNING: no GPU visible. Check the kernel's accelerator setting.")
    return ""


def install_compatible_torch(capability: str) -> None:
    """Replace the preinstalled torch with one that has kernels for this GPU.

    Kaggle's P100 is sm_60 (Pascal) and the preinstalled torch 2.10+cu128 ships
    sm_70 upward, so the first convolution dies with cudaErrorNoKernelImageForDevice.
    It is not a slowdown and not a fallback -- nothing runs at all.

    The cu121 wheels are the last ones built with Pascal kernels, so that is what gets
    installed. This is a real cost, roughly two minutes and a couple of gigabytes per
    run, and it is only paid when the check above finds a mismatch.
    """
    print(f"installing a torch build with {capability} kernels", flush=True)
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q",
         "torch==2.4.1", "torchvision==0.19.1",
         "--index-url", "https://download.pytorch.org/whl/cu121"],
    )
    if result.returncode != 0:
        raise SystemExit("Could not install a torch build compatible with this GPU.")

    # Verify in a fresh interpreter: the already-imported torch cannot be swapped in
    # place, and asserting the new build actually carries the capability is the only
    # way to know the reinstall did what it claimed.
    check = subprocess.run(
        [sys.executable, "-c",
         "import torch;a=torch.cuda.get_device_capability(0);"
         "s=f'sm_{a[0]}{a[1]}';print(s, s in torch.cuda.get_arch_list())"],
        capture_output=True, text=True,
    )
    print("after reinstall:", check.stdout.strip() or check.stderr.strip()[:200])
    if "True" not in check.stdout:
        raise SystemExit(f"Reinstalled torch still lacks {capability} kernels.")


def resolve_corpus() -> Path:
    """Find the attached corpus, and say what IS there when it is missing.

    Kaggle mounts a dataset under /kaggle/input using a name derived from the dataset,
    and guessing that name wrongly produces "corpus not attached" -- which reads as a
    missing dataset rather than a wrong path, and sends you to fix the wrong thing.
    Directories are also zipped per-split by the uploader, so the mount may hold
    train.zip rather than train/, and those are unpacked here.
    """
    root = Path("/kaggle/input")
    if not root.is_dir():
        raise SystemExit("No /kaggle/input at all; the kernel has no attached data.")

    # Search for the directory that actually holds the corpus rather than trusting a
    # guessed name. Kaggle nests the mount (observed: /kaggle/input/datasets/<name>),
    # and the depth is not something to hardcode -- the marker is the content.
    def looks_like_corpus(path: Path) -> bool:
        if any((path / split).is_dir() for split in ("train", "val", "test")):
            return True
        return bool(list(path.glob("*.zip")))

    found = None
    if CORPUS.is_dir() and looks_like_corpus(CORPUS):
        found = CORPUS
    else:
        for depth in range(4):
            for candidate in sorted(root.glob("/".join(["*"] * (depth + 1)))):
                if candidate.is_dir() and looks_like_corpus(candidate):
                    found = candidate
                    break
            if found is not None:
                break
    if found is None:
        listing = [str(q.relative_to(root)) for q in root.rglob("*") if q.is_dir()][:40]
        raise SystemExit(f"No corpus under /kaggle/input. Directories seen: {listing}")
    if found != CORPUS:
        print(f"corpus expected at {CORPUS}, found at {found}")

    archives = sorted(found.glob("*.zip"))
    if archives:
        # Kaggle serves the zips as-is; the trainer wants split directories.
        import zipfile

        unpacked = SCRATCH / "corpus"
        unpacked.mkdir(parents=True, exist_ok=True)
        for archive in archives:
            target = unpacked / archive.stem
            if target.is_dir():
                continue
            print(f"unpacking {archive.name}", flush=True)
            with zipfile.ZipFile(archive) as bundle:
                bundle.extractall(target)
        for extra in found.glob("*.yaml"):
            shutil.copy2(extra, unpacked / extra.name)
        print("corpus ready at", unpacked, sorted(p.name for p in unpacked.iterdir()))
        return unpacked
    return found


def ensure_repo() -> None:
    """Clone the code the kernel is supposed to run.

    A kernel is a bare script on a fresh machine: nothing about the repository is
    present unless it is fetched. Cloning at a pinned commit rather than tracking main
    means a kernel re-run months later trains the same code, and a result can be traced
    to a SHA rather than to whatever main happened to be that day.
    """
    if REPO.is_dir():
        return
    commit = os.environ.get("ODK_COMMIT", "main")
    subprocess.run(
        ["git", "clone", "--quiet", "https://github.com/00PrabalK00/OpenDroneKit.git", str(REPO)],
        check=True,
    )
    subprocess.run(["git", "checkout", "--quiet", commit], cwd=REPO, check=True)
    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
                          capture_output=True, text=True).stdout.strip()
    print("repo at commit", head)


def main() -> int:
    missing = report_environment()
    if missing:
        install_compatible_torch(missing)
    ensure_repo()
    corpus = resolve_corpus()

    command = [
        sys.executable, "-m", "training.train_cls",
        "--config", str(REPO / "training" / "configs" / "crack_cls.yaml"),
        "--data-root", str(corpus),
        "--output-dir", str(OUT),
    ]
    print("running:", " ".join(command), flush=True)
    result = subprocess.run(command, cwd=REPO)
    if result.returncode != 0:
        raise SystemExit(f"Training failed with exit code {result.returncode}.")

    collect_outputs()
    return 0


def collect_outputs() -> None:
    """Copy named artefacts to /kaggle/working, and only those.

    Kaggle packages everything under /kaggle/working as the kernel's output. A previous
    run left the corpus there and produced a 161 MB download of data that was already on
    disk locally, which then stalled. Named files only, and a printed manifest so the
    size of what is about to be downloaded is visible in the log.
    """
    wanted = ["best.pt", "last.pt", "best.pth", "summary.json", "metrics.json", "results.csv"]
    staged = Path("/kaggle/working")
    manifest = []
    for name in wanted:
        for source in OUT.rglob(name):
            target = staged / source.name
            if source.resolve() == target.resolve():
                continue
            shutil.copy2(source, target)
            manifest.append({"file": target.name, "bytes": target.stat().st_size})

    total = sum(item["bytes"] for item in manifest)
    print(json.dumps({"outputs": manifest, "total_bytes": total}, indent=2))
    if not manifest:
        print("WARNING: training reported success but produced no recognised artefact.")


if __name__ == "__main__":
    raise SystemExit(main())
