"""Kaggle kernel: train crack_cls (classification).

Generated by tools/kaggle_kernel.py. Edit the config in the repository, not this file --
a change made here is invisible to everyone reading the repo.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path("/kaggle/working/OpenDroneKit")
CORPUS = Path("/kaggle/input/odk-crack-cls-corpus")
OUT = Path("/kaggle/working/artifacts")
OUT.mkdir(parents=True, exist_ok=True)


def report_environment() -> None:
    """Print the environment before training rather than after it fails.

    A torch build that does not support the assigned GPU's compute capability still
    runs; it just falls back and takes far longer, which reads as a slow dataset rather
    than a broken install. Printing this at the top of the log makes it obvious.
    """
    import torch

    print("torch     :", torch.__version__)
    print("cuda built:", torch.version.cuda)
    print("cuda avail:", torch.cuda.is_available())
    if torch.cuda.is_available():
        index = torch.cuda.current_device()
        major, minor = torch.cuda.get_device_capability(index)
        print("device    :", torch.cuda.get_device_name(index))
        print("capability: sm_{}{}".format(major, minor))
        supported = torch.cuda.get_arch_list()
        print("torch arch:", ", ".join(supported))
        if f"sm_{major}{minor}" not in supported:
            print(
                "WARNING: this torch build does not list the device's compute "
                "capability. Training will be far slower than the hardware allows."
            )
    else:
        print("WARNING: no GPU visible. Check the kernel's accelerator setting.")


def ensure_repo() -> None:
    """Clone the code the kernel is supposed to run.

    A kernel is a bare script on a fresh machine: nothing about the repository is
    present unless it is fetched. Cloning at a pinned commit rather than tracking main
    means a kernel re-run months later trains the same code, and a result can be traced
    to a SHA rather than to whatever main happened to be that day.
    """
    if REPO.is_dir():
        return
    commit = os.environ.get("ODK_COMMIT", "main")
    subprocess.run(
        ["git", "clone", "--quiet", "https://github.com/00PrabalK00/OpenDroneKit.git", str(REPO)],
        check=True,
    )
    subprocess.run(["git", "checkout", "--quiet", commit], cwd=REPO, check=True)
    head = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
                          capture_output=True, text=True).stdout.strip()
    print("repo at commit", head)


def main() -> int:
    report_environment()
    ensure_repo()
    if not CORPUS.is_dir():
        raise SystemExit(
            f"Corpus not attached at {CORPUS}. Add the dataset to the kernel's inputs."
        )

    command = [
        sys.executable, "-m", "training.train_cls",
        "--config", str(REPO / "training" / "configs" / "crack_cls.yaml"),
        "--data-root", str(CORPUS),
        "--output-dir", str(OUT),
    ]
    print("running:", " ".join(command), flush=True)
    result = subprocess.run(command, cwd=REPO)
    if result.returncode != 0:
        raise SystemExit(f"Training failed with exit code {result.returncode}.")

    collect_outputs()
    return 0


def collect_outputs() -> None:
    """Copy named artefacts to /kaggle/working, and only those.

    Kaggle packages everything under /kaggle/working as the kernel's output. A previous
    run left the corpus there and produced a 161 MB download of data that was already on
    disk locally, which then stalled. Named files only, and a printed manifest so the
    size of what is about to be downloaded is visible in the log.
    """
    wanted = ["best.pt", "last.pt", "best.pth", "summary.json", "metrics.json", "results.csv"]
    staged = Path("/kaggle/working")
    manifest = []
    for name in wanted:
        for source in OUT.rglob(name):
            target = staged / source.name
            if source.resolve() == target.resolve():
                continue
            shutil.copy2(source, target)
            manifest.append({"file": target.name, "bytes": target.stat().st_size})

    total = sum(item["bytes"] for item in manifest)
    print(json.dumps({"outputs": manifest, "total_bytes": total}, indent=2))
    if not manifest:
        print("WARNING: training reported success but produced no recognised artefact.")


if __name__ == "__main__":
    raise SystemExit(main())
