"""Generate a Kaggle kernel that trains one OpenDroneKit config.

Kaggle is the free tier of this project's compute, and a kernel is the only way to use
it non-interactively. This writes the two files the Kaggle API wants -- a script and a
``kernel-metadata.json`` -- for a named training config, so a run can be pushed without
hand-editing a notebook and without the settings drifting from the config in the repo.

Two things here are reactions to what actually went wrong last time.

The output whitelist. A previous run copied both prepared corpora into the kernel's
output directory, which made the result 161 MB of data we already had and stalled the
download for three hours before anyone noticed. A kernel's output should be the weights,
the metrics and the log, and nothing that was already an input, so this generates a
finalisation step that copies named artefacts out and refuses to sweep a directory.

The environment check. The same run silently trained on a GPU whose compute capability
the installed torch did not support, and only self-healed because Kaggle happened to
update. The generated kernel prints torch, CUDA and device capability before training so
that mismatch appears at the top of the log rather than as a mysterious slowdown.

    python -m tools.kaggle_kernel solar_thermal_cls --username <kaggle-user>
    python -m tools.kaggle_kernel pvel_ad_yolo11l --username <kaggle-user> --gpu
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "training" / "configs"
OUTPUT_ROOT = ROOT / "training" / "kaggle"

# Which trainer module runs a config, keyed by a marker in the config's own contents.
# Reading the config rather than guessing from the file name means a renamed config
# cannot quietly end up on the wrong trainer.
TRAINER_FOR_KIND = {
    "classification": "training.train_cls",
    "detection": "training.train_det",
    "segmentation": "training.train_seg",
    "semantic": "training.train_shared_semantic",
}


class KernelError(ValueError):
    pass


def infer_kind(config_text: str) -> str:
    """Work out which trainer a config belongs to from what it declares."""
    if "model_id: yolo" in config_text:
        return "detection"
    if "encoder: dinov2" in config_text:
        return "semantic"
    if "model_id: nvidia/mit-" in config_text:
        return "segmentation"
    if re.search(r"^model_id: (resnet|efficientnet|convnext|vit)", config_text, re.MULTILINE):
        return "classification"
    raise KernelError(
        "Cannot tell which trainer this config needs. Expected a model_id naming a YOLO "
        "checkpoint, a SegFormer encoder, a torchvision backbone, or a dinov2 encoder."
    )


def kernel_script(config_name: str, kind: str, dataset_slug: str) -> str:
    """The script the kernel runs, as text."""
    trainer = TRAINER_FOR_KIND[kind]
    return f'''"""Kaggle kernel: train {config_name} ({kind}).

Generated by tools/kaggle_kernel.py. Edit the config in the repository, not this file --
a change made here is invisible to everyone reading the repo.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path("/kaggle/working/OpenDroneKit")
CORPUS = Path("/kaggle/input/{dataset_slug}")
OUT = Path("/kaggle/working/artifacts")
OUT.mkdir(parents=True, exist_ok=True)


def report_environment() -> None:
    """Print the environment before training rather than after it fails.

    A torch build that does not support the assigned GPU's compute capability still
    runs; it just falls back and takes far longer, which reads as a slow dataset rather
    than a broken install. Printing this at the top of the log makes it obvious.
    """
    import torch

    print("torch     :", torch.__version__)
    print("cuda built:", torch.version.cuda)
    print("cuda avail:", torch.cuda.is_available())
    if torch.cuda.is_available():
        index = torch.cuda.current_device()
        major, minor = torch.cuda.get_device_capability(index)
        print("device    :", torch.cuda.get_device_name(index))
        print("capability: sm_{{}}{{}}".format(major, minor))
        supported = torch.cuda.get_arch_list()
        print("torch arch:", ", ".join(supported))
        if f"sm_{{major}}{{minor}}" not in supported:
            print(
                "WARNING: this torch build does not list the device's compute "
                "capability. Training will be far slower than the hardware allows."
            )
    else:
        print("WARNING: no GPU visible. Check the kernel's accelerator setting.")


def main() -> int:
    report_environment()
    if not CORPUS.is_dir():
        raise SystemExit(
            f"Corpus not attached at {{CORPUS}}. Add the dataset to the kernel's inputs."
        )

    command = [
        sys.executable, "-m", "{trainer}",
        "--config", str(REPO / "training" / "configs" / "{config_name}.yaml"),
        "--data-root", str(CORPUS),
        "--output-dir", str(OUT),
    ]
    print("running:", " ".join(command), flush=True)
    result = subprocess.run(command, cwd=REPO)
    if result.returncode != 0:
        raise SystemExit(f"Training failed with exit code {{result.returncode}}.")

    collect_outputs()
    return 0


def collect_outputs() -> None:
    """Copy named artefacts to /kaggle/working, and only those.

    Kaggle packages everything under /kaggle/working as the kernel's output. A previous
    run left the corpus there and produced a 161 MB download of data that was already on
    disk locally, which then stalled. Named files only, and a printed manifest so the
    size of what is about to be downloaded is visible in the log.
    """
    wanted = ["best.pt", "last.pt", "best.pth", "summary.json", "metrics.json", "results.csv"]
    staged = Path("/kaggle/working")
    manifest = []
    for name in wanted:
        for source in OUT.rglob(name):
            target = staged / source.name
            if source.resolve() == target.resolve():
                continue
            shutil.copy2(source, target)
            manifest.append({{"file": target.name, "bytes": target.stat().st_size}})

    total = sum(item["bytes"] for item in manifest)
    print(json.dumps({{"outputs": manifest, "total_bytes": total}}, indent=2))
    if not manifest:
        print("WARNING: training reported success but produced no recognised artefact.")


if __name__ == "__main__":
    raise SystemExit(main())
'''


def kernel_metadata(
    config_name: str,
    username: str,
    dataset_slug: str,
    *,
    gpu: bool,
    internet: bool,
) -> dict[str, Any]:
    slug = f"{username}/odk-train-{config_name.replace('_', '-')}"
    return {
        "id": slug,
        "title": f"ODK train {config_name}",
        "code_file": f"{config_name}.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": gpu,
        "enable_internet": internet,
        "dataset_sources": [dataset_slug],
        "competition_sources": [],
        "kernel_sources": [],
    }


def generate(
    config_name: str,
    username: str,
    *,
    dataset_slug: str = "",
    gpu: bool = True,
    internet: bool = True,
) -> Path:
    config_path = CONFIGS / f"{config_name}.yaml"
    if not config_path.is_file():
        available = ", ".join(sorted(p.stem for p in CONFIGS.glob("*.yaml")))
        raise KernelError(f"No config named {config_name!r}. Available: {available}")

    kind = infer_kind(config_path.read_text(encoding="utf-8"))
    slug = dataset_slug or f"{username}/odk-{config_name.replace('_', '-')}-corpus"

    target = OUTPUT_ROOT / config_name
    target.mkdir(parents=True, exist_ok=True)
    (target / f"{config_name}.py").write_text(
        kernel_script(config_name, kind, slug.split("/", 1)[-1]), encoding="utf-8"
    )
    (target / "kernel-metadata.json").write_text(
        json.dumps(kernel_metadata(config_name, username, slug, gpu=gpu, internet=internet), indent=2),
        encoding="utf-8",
    )
    return target


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.kaggle_kernel")
    parser.add_argument("config", help="Config stem, e.g. solar_thermal_cls.")
    parser.add_argument("--username", required=True, help="Kaggle username owning the kernel.")
    parser.add_argument("--dataset", default="", help="Corpus dataset slug, user/name.")
    parser.add_argument("--no-gpu", action="store_true")
    parser.add_argument("--no-internet", action="store_true")
    args = parser.parse_args(argv)

    try:
        target = generate(
            args.config,
            args.username,
            dataset_slug=args.dataset,
            gpu=not args.no_gpu,
            internet=not args.no_internet,
        )
    except KernelError as exc:
        print(str(exc))
        return 2

    print(f"Wrote {target}")
    print(f"  push with: kaggle kernels push -p {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
